name: my first terraform deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  my_first_job:
    name: terraform init and plan
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
       
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Terraform Init
        id: init
        working-directory: Infra_Resource_Terraform
        run: terraform init
        
          
      - name: Terraform Validate
        id: validate
        working-directory: Infra_Resource_Terraform
        run: terraform validate
        
          
      - name: Terraform Plan
        id: plan
        working-directory: Infra_Resource_Terraform
        run: terraform plan
        continue-on-error: true
        
 
  
          
          
          
   
